name: sportsforchange
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+17

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  animate_do: ^4.2.0
  flutter_keyboard_visibility: ^6.0.0
  sidebarx: ^0.17.1
  http: ^1.4.0
  mime: ^2.0.0
  http_parser: ^4.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_fonts: ^8.0.1
  image_picker: ^1.1.2
  awesome_dialog: ^3.2.1
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.1.1
  carousel_slider: ^5.1.1
  provider: ^6.1.2
  url_launcher: ^6.1.7
  firebase_core: ^4.4.0
  table_calendar: ^3.2.0
  permission_handler: ^12.0.1
  syncfusion_flutter_datagrid: ^32.2.3
  syncfusion_flutter_xlsio: ^32.2.3
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.3.2
  geocoding: ^4.0.0
  speech_to_text: ^7.0.0

 # camera_with_gps: any

  

  
  font_awesome_flutter: ^10.1.0 
  camera: ^0.11.3
  geolocator: any
  image_editor_plus: ^1.0.6
  video_player: ^2.10.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

     

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/sfcicon.jpeg"
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/fonts/
     - assets/icon/
  #   - images/a_dot_ham.jpeg

