// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaibv786VHT0dUk_hPPSDi5oX32oP4k-M',
    appId: '1:169752099031:web:7fa5e01026ed8800195892',
    messagingSenderId: '169752099031',
    projectId: 'sportsforchangeproject',
    authDomain: 'sportsforchangeproject.firebaseapp.com',
    storageBucket: 'sportsforchangeproject.firebasestorage.app',
    measurementId: 'G-C6G2YKX8CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWOU5DRVgRs0iw_GsBFWmntfYUyY-_FZc',
    appId: '1:169752099031:android:891a4f4ec0f01437195892',
    messagingSenderId: '169752099031',
    projectId: 'sportsforchangeproject',
    storageBucket: 'sportsforchangeproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdlAI_U8pUAVyduagPjnQ5E9X5hMpZGk',
    appId: '1:169752099031:ios:1b71bbf2ba127748195892',
    messagingSenderId: '169752099031',
    projectId: 'sportsforchangeproject',
    storageBucket: 'sportsforchangeproject.firebasestorage.app',
    iosBundleId: 'com.example.sportsdemo',
  );

}