// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDfkhm8RZ37dAYwKEMxrk-kPYNkjEqBEU',
    appId: '1:897066582164:web:350ef390beaff3f27f3481',
    messagingSenderId: '897066582164',
    projectId: 'sportsforchange-35208',
    authDomain: 'sportsforchange-35208.firebaseapp.com',
    storageBucket: 'sportsforchange-35208.firebasestorage.app',
    measurementId: 'G-1KM9Z8S6XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuEt8AezQiAmMz-9hMDLLIMsy40NleHaY',
    appId: '1:897066582164:android:da837837ffaf621f7f3481',
    messagingSenderId: '897066582164',
    projectId: 'sportsforchange-35208',
    storageBucket: 'sportsforchange-35208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN7nDii-1wq98B511I9_iTvtW9-44DyXw',
    appId: '1:897066582164:ios:c90382a15c4857f97f3481',
    messagingSenderId: '897066582164',
    projectId: 'sportsforchange-35208',
    storageBucket: 'sportsforchange-35208.firebasestorage.app',
    iosBundleId: 'com.example.sportsdemo',
  );
}
